### ISSUE TITLE
LDAP login?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-admin#3]
It would be awesome if we could reuse existing authentication services rather than reinventing the wheel. This doesn't work for me right now; can it?
```ruby
require 'rubygems'
require 'net/ldap'
require 'highline/import'

username = ask("username: ")
password = ask("password: ") { |q| q.echo = false }

ldap = Net::LDAP.new
ldap.host = 'asod04.wgbh.org'
ldap.port = 389
ldap.auth(username, password)

if ldap.bind
        puts 'good'
else
        puts 'bad'
end
```

**Comment by Muraszko** [comment]
@mccalluc Put in a service ticket through IT.  Maybe they can walk you through it.

**Comment by mccalluc** [comment]
Filed https://servicedesk.wgbh.org/scripts/texcel/servicewise/customer/conversation.dll?default?58&4502&6752&0&48834#

**Comment by mccalluc** [comment]
moot
